chains:
  mainnet:
    rpc:
      host: https://eth-mainnet.g.alchemy.com/v2/5G7UdpHTbR9ZtKWFVFs0SdEF8gbvdln1
      timeout: 30s
      rps: 10
    chain_id: 1
    block_time: 15s
    block_index_interval: 60s
    explorer_tx_link_format: 'https://etherscan.io/tx/%s'
  joc:
    rpc: 
      host: https://mainnet.japanopenchain.org:8545
      timeout: 20s
      rps: 10
    chain_id: 81
    block_time: 5s
    block_index_interval: 30s
    safe_logs_request: true
    explorer_tx_link_format: 'https://mainnet.japanopenchain.org/tx/%s'
bridges:
  joc-mainnet-amb:
    bridge_mode: AMB
    home: 
      chain: joc
      address: 0x2deC96c28A6e991BAc485D2e191abB91da6F8148
      validator_contract_address: 0xFdf8a9080616e54124Ba248f5B06172Cc315B5D4
      start_block: 3579025
      required_block_confirmations: 20
      max_block_range_size: 2000
    foreign:
      chain: mainnet
      address: 0x2deC96c28A6e991BAc485D2e191abB91da6F8148
      validator_contract_address: 0xFdf8a9080616e54124Ba248f5B06172Cc315B5D4
      start_block: 16716971
      required_block_confirmations: 20
      max_block_range_size: 1000
    alerts:
      stuck_message_confirmation:
      unknown_message_confirmation:
      unknown_message_execution:
      failed_message_execution:
      unknown_information_signature:
      unknown_information_execution:
      stuck_information_request:
      failed_information_request:
      different_information_signatures:
      last_validator_activity:
postgres:
  user: postgres
  password: pass
  host: postgres
  port: 5432
  database: db
log_level: info
presenter:
  host: 0.0.0.0:3333