chains:
  mainnet:
    rpc:
      host: https://mainnet.infura.io/v3/${INFURA_PROJECT_KEY}
      timeout: 30s
      rps: 10
    chain_id: 1
    block_time: 15s
    block_index_interval: 60s
  bsc:
    rpc:
      host: https://bsc-dataseed4.ninicoin.io/
      timeout: 20s
      rps: 10
    chain_id: 56
    block_time: 3s
    block_index_interval: 60s
    safe_logs_request: true
  kovan:
    rpc:
      host: https://kovan.poa.network
      timeout: 30s
      rps: 10
    chain_id: 42
    block_time: 5s
    block_index_interval: 60s
  xdai:
    rpc:
      host: https://dai.poa.network/oe-only
      timeout: 20s
      rps: 10
    chain_id: 100
    block_time: 5s
    block_index_interval: 30s
  poa:
    rpc:
      host: https://core.poa.network
      timeout: 20s
      rps: 10
    chain_id: 99
    block_time: 5s
    block_index_interval: 30s
  sokol:
    rpc:
      host: https://sokol.poa.network
      timeout: 20s
      rps: 10
    chain_id: 77
    block_time: 5s
    block_index_interval: 30s
  rinkeby:
    rpc:
      host: https://rinkeby.infura.io/v3/${INFURA_PROJECT_KEY}
      timeout: 20s
      rps: 10
    chain_id: 4
    block_time: 15s
    block_index_interval: 60s
bridges:
  xdai-amb:
    home:
      chain: xdai
      address: 0x75Df5AF045d91108662D8080fD1FEFAd6aA0bb59
      start_block: 7408640
      required_block_confirmations: 12
      max_block_range_size: 2000
    foreign:
      chain: mainnet
      address: 0x4C36d2919e407f0Cc2Ee3c993ccF8ac26d9CE64e
      start_block: 9130277
      required_block_confirmations: 12
      max_block_range_size: 1000
    alerts:
      unknown_message_confirmation:
      unknown_message_execution:
      stuck_message_confirmation:
        foreign_start_block: 11907302
      failed_message_execution:
        home_start_block: 17518126
        foreign_start_block: 13026966
      unknown_information_signature:
      unknown_information_execution:
      stuck_information_request:
      failed_information_request:
      different_information_signatures:
  test-amb:
    home:
      chain: sokol
      address: 0xFe446bEF1DbF7AFE24E81e05BC8B271C1BA9a560
      start_block: 9849619
      required_block_confirmations: 12
      max_block_range_size: 10000
    foreign:
      chain: kovan
      address: 0xFe446bEF1DbF7AFE24E81e05BC8B271C1BA9a560
      start_block: 12372929
      required_block_confirmations: 12
      max_block_range_size: 10000
    alerts:
      stuck_message_confirmation:
        foreign_start_block: 25437689
      unknown_message_confirmation:
        home_start_block: 10666885
      unknown_message_execution:
        foreign_start_block: 13603170
      unknown_information_signature:
      unknown_information_execution:
      stuck_information_request:
      failed_information_request:
        home_start_block: 21822099
      different_information_signatures:
  bsc-xdai-amb:
    home:
      chain: xdai
      address: 0x162E898bD0aacB578C8D5F8d6ca588c13d2A383F
      start_block: 14496725
      required_block_confirmations: 12
      max_block_range_size: 10000
    foreign:
      chain: bsc
      address: 0x05185872898b6f94AA600177EF41B9334B1FA48B
      start_block: 4792263
      required_block_confirmations: 12
      max_block_range_size: 1000
    alerts:
      stuck_message_confirmation:
      failed_message_execution:
        home_start_block: 15650488
        foreign_start_block: 6984913
      unknown_message_confirmation:
      unknown_message_execution:
      unknown_information_signature:
      unknown_information_execution:
      stuck_information_request:
      failed_information_request:
      different_information_signatures:
  rinkeby-xdai-amb:
    home:
      chain: xdai
      address: 0xc38D4991c951fE8BCE1a12bEef2046eF36b0FA4A
      start_block: 10030211
      required_block_confirmations: 12
      max_block_range_size: 20000
    foreign:
      chain: rinkeby
      address: 0xD4075FB57fCf038bFc702c915Ef9592534bED5c1
      start_block: 6529875
      required_block_confirmations: 4
      max_block_range_size: 20000
    alerts:
      stuck_message_confirmation:
        foreign_start_block: 8360609
      unknown_message_confirmation:
      unknown_message_execution:
      unknown_information_signature:
      unknown_information_execution:
      stuck_information_request:
      failed_information_request:
      different_information_signatures:
  poa-xdai-amb:
    home:
      chain: xdai
      address: 0xc2d77d118326c33BBe36EbeAbf4F7ED6BC2dda5c
      start_block: 17976497
      required_block_confirmations: 12
      max_block_range_size: 10000
    foreign:
      chain: poa
      address: 0xB2218bdEbe8e90f80D04286772B0968ead666942
      start_block: 23152190
      required_block_confirmations: 12
      max_block_range_size: 10000
    alerts:
      stuck_message_confirmation:
      failed_message_execution:
      unknown_message_confirmation:
      unknown_message_execution:
      unknown_information_signature:
      unknown_information_execution:
      stuck_information_request:
      failed_information_request:
      different_information_signatures:
  eth-bsc-amb:
    home:
      chain: bsc
      address: 0x6943A218d58135793F1FE619414eD476C37ad65a
      start_block: 2756521
      required_block_confirmations: 12
      max_block_range_size: 1000
    foreign:
      chain: mainnet
      address: 0x07955be2967B655Cf52751fCE7ccC8c61EA594e2
      start_block: 11375619
      required_block_confirmations: 12
      max_block_range_size: 10000
    alerts:
      stuck_message_confirmation:
      failed_message_execution:
      unknown_message_confirmation:
      unknown_message_execution:
      unknown_information_signature:
      unknown_information_execution:
      stuck_information_request:
      failed_information_request:
      different_information_signatures:
postgres:
  user: postgres
  password: pass
  host: postgres
  port: 5432
  database: db
log_level: info
presenter:
  host: 0.0.0.0:3333
