version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    shm_size: 256mb
  monitor:
    build: .
    env_file:
      - .env
volumes:
  db: