global:
  slack_api_url_file: /etc/prometheus/slack_api_url.txt
receivers:
  - name: slack-default
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: 'Unrecognized alert occurred'
        text: '{{ . }}'
  - name: slack-stuck-message
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.stuck_message.title" . }}'
        text: '{{ template "slack.stuck_message.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-unknown-confirmation
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.unknown_confirmation.title" . }}'
        text: '{{ template "slack.unknown_confirmation.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-unknown-execution
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.unknown_execution.title" . }}'
        text: '{{ template "slack.unknown_execution.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-failed-execution
    slack_configs:
      - send_resolved: false
        channel: '#amb-alerts'
        title: '{{ template "slack.failed_execution.title" . }}'
        text: '{{ template "slack.failed_execution.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-stuck-information-request
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.stuck_information_request.title" . }}'
        text: '{{ template "slack.stuck_information_request.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-unknown-information-signature
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.unknown_information_signature.title" . }}'
        text: '{{ template "slack.unknown_information_signature.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-unknown-information-execution
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.unknown_information_execution.title" . }}'
        text: '{{ template "slack.unknown_information_execution.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-failed-information-request
    slack_configs:
      - send_resolved: false
        channel: '#amb-alerts'
        title: '{{ template "slack.failed_information_request.title" . }}'
        text: '{{ template "slack.failed_information_request.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-different-information-signatures
    slack_configs:
      - send_resolved: false
        channel: '#amb-alerts'
        title: '{{ template "slack.different_information_signatures.title" . }}'
        text: '{{ template "slack.different_information_signatures.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-stuck-erc-to-native-message
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.stuck_erc_to_native_message.title" . }}'
        text: '{{ template "slack.stuck_erc_to_native_message.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-unknown-erc-to-native-confirmation
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.unknown_erc_to_native_confirmation.title" . }}'
        text: '{{ template "slack.unknown_erc_to_native_confirmation.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-unknown-erc-to-native-execution
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.unknown_erc_to_native_execution.title" . }}'
        text: '{{ template "slack.unknown_erc_to_native_execution.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-stuck-contract
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.stuck_contract.title" . }}'
        text: '{{ template "slack.stuck_contract.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-validator-offline
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: '{{ template "slack.validator_offline.title" . }}'
        text: '{{ template "slack.validator_offline.text" . }}'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
  - name: slack-dm
    slack_configs:
      - send_resolved: true
        channel: '#amb-alerts'
        title: 'Monitor application is down'
        actions:
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
route:
  receiver: slack-default
  group_by: [ "..." ]
  routes:
    - receiver: slack-stuck-message
      group_by: [ "alertname", "bridge_id", "chain_id", "block_number", "tx_hash" ]
      matchers:
        - alertname = StuckMessage
    - receiver: slack-unknown-confirmation
      group_by: [ "..." ]
      matchers:
        - alertname = UnknownMessageConfirmation
    - receiver: slack-unknown-execution
      group_by: [ "..." ]
      matchers:
        - alertname = UnknownMessageExecution
    - receiver: slack-failed-execution
      group_by: [ "..." ]
      repeat_interval: 24h
      matchers:
        - alertname = FailedMessageExecution
    - receiver: slack-stuck-information-request
      group_by: [ "alertname", "bridge_id", "chain_id", "block_number", "tx_hash" ]
      matchers:
        - alertname = StuckInformationRequest
    - receiver: slack-unknown-information-signature
      group_by: [ "..." ]
      matchers:
        - alertname = UnknownInformationSignature
    - receiver: slack-unknown-information-execution
      group_by: [ "..." ]
      matchers:
        - alertname = UnknownInformationExecution
    - receiver: slack-failed-information-request
      group_by: [ "..." ]
      repeat_interval: 24h
      matchers:
        - alertname = FailedInformationRequest
    - receiver: slack-different-information-signatures
      group_by: [ "..." ]
      matchers:
        - alertname = DifferentInformationSignatures
    - receiver: slack-stuck-erc-to-native-message
      group_by: [ "alertname", "bridge_id", "chain_id", "block_number", "tx_hash", "receiver", "value" ]
      matchers:
        - alertname = StuckErcToNativeMessage
    - receiver: slack-unknown-erc-to-native-confirmation
      group_by: [ "..." ]
      matchers:
        - alertname = UnknownErcToNativeMessageConfirmation
    - receiver: slack-unknown-erc-to-native-execution
      group_by: [ "..." ]
      matchers:
        - alertname = UnknownErcToNativeMessageExecution
    - receiver: slack-validator-offline
      group_by: [ "..." ]
      matchers:
        - alertname = ValidatorOffline
    - receiver: slack-stuck-contract
      group_by: [ "..." ]
      matchers:
        - alertname = StuckContractProgress
    - receiver: slack-dm
      group_by: [ "..." ]
      matchers:
        - alertname = InstanceIsDown
inhibit_rules:
  - target_matchers:
      - alertname =~ .*
  - source_matchers:
      - alertname = InstanceIsDown
    equal: [ "job", "instance" ]
templates:
  - templates/*.tmpl
