global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
      basic_auth:
        username: admin
        password_file: /etc/prometheus/admin_password.txt

rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: "monitor"
    static_configs:
      - targets: ["monitor:2112"]